---
kind: pipeline
type: kubernetes
name: default

steps:
- name: tests
  image: elixir:1.9
  commands:
  - mix local.hex --force && mix local.rebar --force
  - mix deps.get
  - mix test

- name: container
  image: plugins/docker
  settings:
    username:
      from_secret: dcr_username
    password:
      from_secret: dcr_password
    repo: dcr.blackieops.com/jkp
    registry: dcr.blackieops.com
    tag: "${DRONE_COMMIT}"
  when:
    branch:
    - deploy/production

- name: kubeconfig
  image: digitalocean/doctl:1.36
  environment:
    DIGITALOCEAN_ACCESS_TOKEN:
      from_secret: digitalocean_access_token
  commands:
  - doctl kubernetes cluster kubeconfig show prd-dtor > ./do.yaml
  when:
    branch:
    - deploy/production

- name: rollout
  image: bitnami/kubectl:1.15
  commands:
  - kubectl --kubeconfig ./do.yaml set image svc/jkp "jkp=dcr.blackieops.com/jkp:${DRONE_COMMIT}"
  when:
    branch:
    - deploy/production
