# fly.toml file generated for junkpics on 2022-07-23T13:35:29-07:00

app = "junkpics"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  "spring.mustache.suffix" = ".html"
  "junk.picDataService" = "azureblob"
  "azure.storage.accountName" = "junkpicsproduction"
  "azure.storage.blob-endpoint" = "https://junkpicsproduction.blob.core.windows.net"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
