---
name: Run tests
on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: "17"
        cache: maven

    - name: Set up properties file
      run: cp src/main/resources/application.yml.ci src/main/resources/application.yml

    - name: Test with maven
      run: mvn test
